#pragma once

#define TIMERID_BATTLE_INVALIDATE 900
#define ELAPSE_BATTLE_INVALIDATE 10

#define TIMERID_BATTLE_ANIMATION 901
#define ELAPSE_BATTLE_ANIMATION 50

#define TIMERID_BATTLE_ANIMATION_BOSS 902
#define ELAPSE_BATTLE_ANIMATION_BOSS 100

#define TIMERID_BATTLE_MOVE_PLAYER 903
#define ELAPSE_BATTLE_MOVE_PLAYER 10

#define TIMERID_BATTLE_EFFECT 904
#define ELAPSE_BATTLE_EFFECT 50

#define TIMERID_BATTLE_GUI 905
#define ELAPSE_BATTLE_GUI 10

void CALLBACK T_Battle_Invalidate(HWND hWnd, UINT uMsg, UINT idEvent, DWORD dwTime);
void CALLBACK T_Battle_Animate(HWND hWnd, UINT uMsg, UINT idEvent, DWORD dwTime);
void CALLBACK T_Battle_AnimateBoss(HWND hWnd, UINT uMsg, UINT idEvent, DWORD dwTime);
void CALLBACK T_Battle_MovePlayer(HWND hWnd, UINT uMsg, UINT idEvent, DWORD dwTime);
void CALLBACK T_Battle_Effect(HWND hWnd, UINT uMsg, UINT idEvent, DWORD dwTime);
void CALLBACK T_Battle_GUI(HWND hWnd, UINT uMsg, UINT idEvent, DWORD dwTime);
